# Generated by Django 3.1 on 2021-04-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('S', 'Stock'), ('C', 'Crypto')], default='S', max_length=1),
        ),
    ]
