# Generated by Django 3.1 on 2021-04-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
    ]
